<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190830163652 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string 
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void 
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->addSql('CREATE TABLE sitegeist_csvpo_domain_translationoverride (persistence_object_identifier VARCHAR(40) NOT NULL, sourceidentifier VARCHAR(255) NOT NULL, translationidentifier VARCHAR(255) NOT NULL, localeidentifier VARCHAR(255) NOT NULL, translation VARCHAR(255) NOT NULL, INDEX sourceIdentifier_index (sourceIdentifier(255)), UNIQUE INDEX UNIQ_EF1075AE1D71B2699704492C9095C972 (sourceIdentifier, translationIdentifier, localeIdentifier), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void 
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->addSql('DROP TABLE sitegeist_csvpo_domain_translationoverride');
    }
}
