<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20220218155428 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP INDEX sourceIdentifier_index ON sitegeist_csvpo_domain_translationoverride');
        $this->addSql('ALTER TABLE sitegeist_csvpo_domain_translationoverride CHANGE translation translation LONGTEXT NOT NULL');
        $this->addSql('CREATE INDEX sourceIdentifier_index ON sitegeist_csvpo_domain_translationoverride (sourceIdentifier(255))');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP INDEX sourceIdentifier_index ON sitegeist_csvpo_domain_translationoverride');
        $this->addSql('ALTER TABLE sitegeist_csvpo_domain_translationoverride CHANGE translation translation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE INDEX sourceIdentifier_index ON sitegeist_csvpo_domain_translationoverride (sourceidentifier)');
    }
}
